<a href="https://colab.research.google.com/github/R-DK/Repo3/blob/main/PDSA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **WEEK-2**

### **BINARY SEARCH**

In [ ]:
def binarySearch(value, L):  #recursive algorithm
  if L==[]:  # if list empty return false
    return(False)
  
  m = len(L)//2 # middle index

  if value == L[m]: 
    return(True)
  
  if value>L[m]:
    return binarySearch(value, L[m+1:])
  else:
    return binarySearch(value, L[:m])

In [ ]:
L = list(map(int, input().split()))
L.sort()
val = int(input())
if(binarySearch(val, L)):
  print("Found")
else:
  print("Not found")

99 100 1 3 4 88 345 9
10
Not found


###**SELECTION SORT**

In [ ]:
def findMin(L):
  minimum = L[0]
  for index in range(1, len(L)):
    if L[index] < minimum:
      minimum = L[index]
  return minimum

Using a second list

In [ ]:
def selectionSort(L):
  if L==[]:
    return []
  sortedList = []
  length = len(L)
  while(L != []):
    minimum = findMin(L)
    sortedList.append(minimum)
    L.remove(minimum)
  return sortedList

Without using a second list

In [ ]:
def selectionSort(L):
  n = len(L)
  if n<1: # If the list is empty then return empty list
    return L
  for i in range(n):
    # minVal = L[i] # consider the current value as the minimum value
    minPos = i # consider the current postion as minimum value position
    for j in range(i+1, n):
      if L[j] < L[minPos]:
        #minVal = L[j]
        minPos = j  # position of the minimum element in the rest of the list i.e from L[i+1:]
    (L[i], L[minPos]) = (L[minPos], L[i]) 
  return L

In [ ]:
L = [0, 8, 9, 1, 4, 3, 111, 5]
print(selectionSort(L))

[0, 1, 3, 4, 5, 8, 9, 111]


###**INSERTION SORT**

- Iterative version


In [ ]:
def InsertionSort(L):
  n = len(L)
  if(n<1): # If list is empty then return an empty list
    return(L)
  for i in range(n):
    j=i  # consider L[:i] is sorted
    while(j>0 and L[j] < L[j-1]):  # insert L[i] in the correct position
      (L[j], L[j-1]) = (L[j-1], L[j])
      j = j - 1 
    # now L[:i+1] is sorted
  return(L)

In [ ]:
L = list(map(int, input().split()))
print(InsertionSort(L))

7 8 0 2 4 1 8 10
[0, 1, 2, 4, 7, 8, 8, 10]


###**MERGE SORT**
- Efficient than insertion and selection sort
- Divide and conquer strategy
- Recursive

- Own solution for Merge function

In [ ]:
def Merge(L1, L2):
  (len1, len2) = (len(L1), len(L2))

  (sortedList, i, j) = ([], 0, 0)

  while(i<len1 and j<len2):
    if(L1[i] <= L2[j]):
      sortedList.append(L1[i])
      i+=1
    else:
      sortedList.append(L2[j])
      j+=1

  while(i<len1):
    sortedList.append(L1[i])
    i+=1

  while(j<len2):
    sortedList.append(L2[j])
    j+=1

  return(sortedList)

- Lecture solution for Merge function

In [ ]:
def Merge(A, B):
  m = len(A)
  n = len(B)

  (C, i, j, k) = ([], 0, 0, 0)

  while(k<(m+n)):
    if(i==m):
      C.extend(B[j:])
      k = k + (n-j)
    elif(j==n):
      C.extend(A[i:])
      k = k + (m-i)
    elif(A[i] < B[j]):
      C.append(A[i]) 
      i += 1
      k += 1
    elif(A[i] >= B[j]):
      C.append(B[j])
      j += 1
      k += 1
  return C

In [ ]:
def MergeSort(L):
  if len(L)<=1:
    return(L)

  mid = len(L)//2
  
  left = MergeSort(L[:mid])
  right = MergeSort(L[mid:])

  sortedList = Merge(left, right)

  return(sortedList)

In [ ]:
L = list(map(int, input().split()))
print(MergeSort(L))

4 5 1 3 2 6
[1, 2, 3, 4, 5, 6]


###**QUICK SORT**
- Divide and conquer algorithhm
- O(nlogn) time
- No merging operation
- No extra cost like merge sort

In [ ]:
def quickSort(L, l, r):
  if r-l<=1:
    return(L)
  (pivot, lower, upper) = (L[l], l+1, l+1)
  for i in range(l+1, r):
    if L[i] > pivot:
      upper = upper + 1
    else:
      (L[i], L[lower]) = (L[lower], L[i])
      (lower, upper) = (lower+1, upper+1)
  (L[l], L[lower-1]) = (L[lower-1], L[l])
  lower = lower - 1
  quickSort(L, l, lower)
  quickSort(L, lower+1, upper)
  return(L)

In [ ]:
print(quickSort([3, 7, 1, 9, 2, 4, 8, 5], 0, 8))

[1, 2, 3, 4, 5, 7, 8, 9]


###**LINKED LIST**

In [ ]:
class Node:
  def __init__(self, v = None):
    self.value = v
    self.next = None
  
  def isEmpty(self):
    if(self.value == None):
      return(True)
    else:
      return(False)
  
  def append(self, v):   # recursive implementation of append
    if(self.isEmpty()):
      self.value = v
    elif(self.next==None):
      self.next = Node(v)
    else:
      self.next.append(v)
    return

  def appendi(self, v):   # iterative implementation of append
    if(self.isEmpty()):
      self.value = v
      return
    temp = self
    while(temp.next != None):
      temp = temp.next
    temp.next = Node(v)
    return

  def insert(self, v):
    if(self.isEmpty()):
      self.value = v
      return

    newNode = Node(v)
    (self.value, newNode.value) = (newNode.value, self.value)
    (newNode.next, self.next) = (self.next, newNode)

    return

  def delete(self, v):   # iterative implementation of delete
    if(self.isEmpty()):
      return

    if(self.value == v):
      self.value = None
      if(self.next != None):
        self.value = self.next.value
        self.next = self.next.next
      return

    curr = self
    prev = None
    while(curr.value != v):
      prev = curr
      curr = curr.next
    prev.next = curr.next
    curr.next = None
    return

  def deletei(self, v):  # recursive implementation of delete
    if(self.isEmpty()):
      return
    
    if(self.value == v):
      self.value = None
      if(self.next != None):
        self.value = self.next.value
        self.next = self.next.next
      return
    else:
      self.next.deletei(v)
      if(self.next.value == None):
        self.next = None
    return

  def printList(self):
    if(self.isEmpty()):
      print('List Empty')
      return
    curr = self
    while(curr):
      print(curr.value, end=' ')
      curr = curr.next

In [ ]:
n = int(input('No of elements: '))
head = Node()
for i in range(n):
  data = int(input())
  head.appendi(data)
head.insert(int(input()))
head.delete(3)
head.printList()

No of elements: 5
1
2
3
4
5
0
0 1 2 4 5 

### List comprehension

In [ ]:
zeroMatrix = [[0 for i in range(3)] for j in range(3)]
zeroMatrix

[[0, 0, 0], [0, 0, 0], [0, 0, 0]]

### NUMPY ARRAYS
- Numpy library provides arrays

In [ ]:
import numpy as np

In [ ]:
zeroArray = np.zeros(shape=(3, 3)) # creates an array of zeros. 3 -> rows, 3-> columns
zeroArray

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
newArray = np.array([[1, 0], [0, 1]]) # converts the given sequence into an array
newArray

array([[1, 0],
       [0, 1]])

#**WEEK-4**

### INTRODUCTION TO GRAPHS



In [ ]:
import numpy as np

In [ ]:
z = np.zeros(shape=(10, 10))
z

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

**Adjacency matrix**


In [ ]:
edges = [(0,1),(0,4),(1,2),(2,0),(3,4),(3,6),  # edges of the graph Airline route (directed graph)
         (4,0),(4,3),(4,7),(5,3),(5,7),(6,5),  # 10 vertices V = {0,1,...,8,9}
         (7,4),(7,8),(8,5),(8,9),(9,8)]

In [ ]:
edges = [(0,1),(0,2),(0,4),(1,0),(1,2),(2,0),(2,1),(3,4),(3,5),
         (3,6),(4,0),(4,3),(4,7),(5,3),(5,6),(5,7),(5,8),(6,3),
         (6,5),(7,4),(7,5),(7,8),(8,5),(8,7),(8,9),(9,8)]

In [ ]:
Amatrix = np.zeros(shape=(10, 10)) # creating an adjacency matrix with all elements being 0 initially
for i, j in edges:
  Amatrix[i][j] = 1 # setiing 1 for A[i, j] if there is an edge from i to j
Amatrix # printing the adjacency matrix of the given graph

array([[0., 1., 1., 0., 1., 0., 0., 0., 0., 0.],
       [1., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 1., 1., 0., 0., 0.],
       [1., 0., 0., 1., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0., 0., 1., 1., 1., 0.],
       [0., 0., 0., 1., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 1., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1., 0., 1., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.]])

**Finding neighbours of a given vertex of a graph**

In [ ]:
def neighbours(Amat, i):
  nghbrs = []
  (row, col) = Amat.shape # gives the dimension of the matrix
  for j in range(col):
    if(Amat[i][j]==1):
      nghbrs.append(j)
  return(nghbrs)

**Queue**

In [ ]:
class Queue:
  def __init__(self): # creates an empty queue when an object is created
    self.queue = []
  
  def addq(self, v): # adds an element to the rear end of the queue
    self.queue.append(v)
  
  def delq(self):  #deletes an element from the front of the queue
    v = None
    if not self.isEmpty():
      v = self.queue[0]
      self.queue = self.queue[1:]
    return(v)

  def isEmpty(self): # checks if the queue is empty
    return(self.queue == [])

  def __str__(self): #returns string form of the queue if we try to print the object
    return(str(self.queue)) 

**How does a queue work?**

In [ ]:
# create an object for class Queue
q = Queue()

# insert elements to the queue
for i in range(3):
  q.addq(i) # adds element to the rear end of the queue
  print(q) # prints the queue at the current stage
print(q.isEmpty()) #checks if the queue is empty

[0]
[0, 1]
[0, 1, 2]
False


In [ ]:
for i in range(3):
  print(q.delq(), q) #deletes an element from the front of the queue
print(q.isEmpty())

0 [1, 2]
1 [2]
2 []
True


## Breadth First Search(BFS)

In [ ]:
def BFS(Amat, v):
  visited = {}
  (row, col) = Amat.shape
  for i in range(row):
    visited[i] = False 
  q = Queue() 

  visited[v] = True
  q.addq(v)

  while(not q.isEmpty()):
    explore = q.delq()
    neighbourVertices = neighbours(Amat, explore)
    for vertex in neighbourVertices:
      if(not visited[vertex]):
        visited[vertex] = True
        q.addq(vertex)
  
  return(visited)

In [ ]:
BFS(Amatrix, 3)

{0: True,
 1: True,
 2: True,
 3: True,
 4: True,
 5: True,
 6: True,
 7: True,
 8: True,
 9: True}

**Adjacency List**

In [ ]:
AList = {}
for i, j in edges:
  if i not in AList.keys():
    AList[i] = [j]
  else:
    AList[i] += [j]
AList 

{0: [1, 2, 4],
 1: [0, 2],
 2: [0, 1],
 3: [4, 5, 6],
 4: [0, 3, 7],
 5: [3, 6, 7, 8],
 6: [3, 5],
 7: [4, 5, 8],
 8: [5, 7, 9],
 9: [8]}

**BFSListPath**

In [ ]:
def BFSListPath(Alist, i):
  #(visited, parent) = ({}, {})  #visited -> maintains visited vertices and parent contains parents of each vertex
  (level, parent) = ({}, {}) # level->maintains the level of  each vertex from the starting vertex and parent maintains the parent of each vertex
  for vertex in Alist.keys():
    #visited[vertex] = False
    level[vertex] = -1
    parent[vertex] = -1
  q = Queue()

  #visited[i] = True 
  level[i] = 0 # level of the starting vertex is 0
  q.addq(i)

  while(not q.isEmpty()):
    explore = q.delq()
    for v in Alist[explore]:
      #if(not visited[v]):
      if(level[v] == -1):
        #visited[v] = True 
        level[v] = level[explore] + 1 # level of a adjacent vertex is 1 more than the level of it's parent
        parent[v] = explore
        q.addq(v) 
  
  #return(visited, parent)
  return(level, parent)

In [ ]:
BFSListPath(AList, 7)

({0: 2, 1: 3, 2: 3, 3: 2, 4: 1, 5: 1, 6: 2, 7: 0, 8: 1, 9: 2},
 {0: 4, 1: 0, 2: 0, 3: 4, 4: 7, 5: 7, 6: 5, 7: -1, 8: 7, 9: 8})

###**Depth First Search(DFS)**
Recursive implementation

Using adjacency matrix

In [ ]:
(visited, parent) = ({}, {}) # initialized globaly

In [ ]:
def DFSInitGlobaly(Amat):
  (rows, cols) = Amat.shape
  for v in range(rows):
    visited[v] = False
    parent[v] = -1 
  return

In [ ]:
def DFS(Amat, v):
  visited[v] = True  #sets visited to true

  for vertex in neighbours(Amat, v):
    if(not visited[vertex]):
      parent[vertex] = v   
      DFS(Amat, vertex)  # suspends exploration of v and goes to vertex
  return

In [ ]:
DFSInitGlobaly(Amatrix)

In [ ]:
DFS(Amatrix, 4)  # starting vertex is 4

In [ ]:
visited, parent

({0: True,
  1: True,
  2: True,
  3: True,
  4: True,
  5: True,
  6: True,
  7: True,
  8: True,
  9: True},
 {0: 4, 1: 0, 2: 1, 3: 4, 4: -1, 5: 3, 6: 5, 7: 5, 8: 7, 9: 8})

Using Adjacency List

In [ ]:
(visited, parent) = ({}, {})

In [ ]:
def DFSInitList(Alist):
  for i in Alist.keys():
    visited[i] = False
    parent[i] = -1

In [ ]:
def DFSlist(Alist, v):
  visited[v] = True

  for vertex in Alist[v]:
    if(not visited[vertex]):
      parent[vertex] = v
      DFSlist(Alist, vertex)
  return

In [ ]:
DFSInitList(AList)

In [ ]:
DFSlist(AList, 4)

In [ ]:
visited, parent

({0: True,
  1: True,
  2: True,
  3: True,
  4: True,
  5: True,
  6: True,
  7: True,
  8: True,
  9: True},
 {0: 4, 1: 0, 2: 1, 3: 4, 4: -1, 5: 3, 6: 5, 7: 5, 8: 7, 9: 8})

###**Identifying connected components**
- Assign each vertex a component number
- Start BFS/DFS from vertex 0
    - Assign the component number of vertex 0 for all the nodes that are reachable from vertex 0
-  Pick the smallest unvisited node j
  - Increment the component number by 1
  - Run BFS/DFS from node j
  - Assign each visited node component number 1
- Repeat, until all nodes are visited

**BFS version of identifying components**

In [ ]:
def AdjacencyList(edges):
  AList = {}
  for i, j in edges:
    if(i not in AList.keys()):
      if(j==-1):
        AList[i] = []
      else:
        AList[i] = [j]
    else:
      AList[i] += [j]
  return(AList)

In [ ]:
def BFSList(AList, v):
  visited = {}
  for i in AList.keys():
    visited[i] = False
  q = Queue()

  visited[v] = True
  q.addq(v)

  while(not q.isEmpty()):
    explore = q.delq()
    for vertex in AList[explore]:
      if(not visited[vertex]):
        q.addq(vertex)
        visited[vertex] = True
  return(visited)

In [ ]:
def Components(AList):
  (components, visited) = ({}, {})
  for i in AList.keys():
    components[i] = -1
  
  (compid, seen) = (0, 0)
  maxKey = max(AList.keys())
  while(seen <= maxKey):
    startv = min([i for i in AList.keys() if components[i]==-1])
    visited = BFSList(AList, startv)

    for k in visited.keys():
      if(visited[k]==True):
        seen += 1
        components[k] = compid
    compid += 1
  return(components)

In [ ]:
edges = [(0,1), (0,4), (1, 0), (4,0),(4,8),(4,9),(8,4),(8,9),(9,8), (2, 3),
                  (2,6),(2,7),(3,2),(3,7),(6,2),(6,7),(6,10),(7,2),(7,3),(7,6),(7,10),(7,11),
                  (10,6),(10,7),(11,7),(5, -1)]

In [ ]:
AList = AdjacencyList(edges)
components = Components(AList)
components.order

{0: 0, 1: 0, 2: 1, 3: 1, 4: 0, 5: 2, 6: 1, 7: 1, 8: 0, 9: 0, 10: 1, 11: 1}

In [ ]:
componentSet = set()
for compid in components.values():
  componentSet.add(compid)
if(len(componentSet)==1):
  print('Connected Graph')
else:
  print('Disconnected graph')

Disconnected graph


###**TOPOLOGICAL SORT**

In [ ]:
import random

In [ ]:
def topologicalsort(Amat):
  indegree = {}
  toposortlist = []
  (row, col) = Amat.shape
  for j in range(col):
    indegree[j] = 0
    for i in range(row):
      if Amat[i, j] == 1:
        indegree[j] += 1
  
  for i in range(row):
    #v = random.choice([k for k in indegree.keys() if indegree[k]==0])
    v = min([k for k in indegree.keys() if indegree[k]==0])
    toposortlist.append(v)
    indegree[v] -= 1
    for k in range(col):
      if(Amat[v, k] == 1):
        indegree[k] -= 1
  
  return(toposortlist)

In [ ]:
dagedges = [(0,2),(0,3),(0,4),(1,2),(1,7),(2,5),(3,5),(3,7),(4,7),(5,6),(6,7), (7,-1)]

In [ ]:
import numpy as np

In [ ]:
Amatrix = np.zeros(shape=(8,8))
for i, j in dagedges:
  Amatrix[i, j] = 1
Amatrix

array([[0., 0., 1., 1., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
topologicalsort(Amatrix)

[0, 1, 2, 3, 4, 5, 6, 7]

In [ ]:
def AdjacencyList(edges):
  AList = {}
  for i, j in edges:
    if i not in AList.keys():
      if(j==-1):
        AList[i] = []
      else:
        AList[i] = [j]
    else:
      AList[i] += [j]
  return(AList)

### Topological sort using Adjacency List

Time complexity : O(m+n)

In [ ]:
def topologicalsortlist(AList):

  (indegree, toposortlist) = ({}, [])

  for u in AList.keys():
    indegree[u] = 0
  for u in AList.keys():
    for v in AList[u]:
      indegree[v] += 1

  zerodegreeq = Queue()
  for u in AList.keys():
    if indegree[u] == 0:
      zerodegreeq.addq(u)

  while(not zerodegreeq.isEmpty()):
    j = zerodegreeq.delq()
    indegree[j] -= 1
    toposortlist.append(j)
    for v in AList[j]:
      indegree[v] -= 1
      if indegree[v] == 0:
        zerodegreeq.addq(v)
  
  return(toposortlist)

In [ ]:
AList = AdjacencyList(dagedges)
AList

{0: [2, 3, 4], 1: [2, 7], 2: [5], 3: [5, 7], 4: [7], 5: [6], 6: [7], 7: []}

In [ ]:
topologicalsortlist(AList)

[0, 1, 3, 4, 2, 5, 6, 7]

###**Longest path in DAG**

In [ ]:
def longestpath(AList):
  (indegree, longestpathto, toposortlist) = ({}, {}, [])
  for u in AList.keys():
    indegree[u] = 0
    longestpathto[u] = 0
  for u in AList.keys():
    for v in AList[u]:
      indegree[v] += 1
  
  longestpathq = Queue()
  for u in AList.keys():
    if(indegree[u]==0):
      longestpathq.addq(u)
  
  while(not  longestpathq.isEmpty()):
    u = longestpathq.delq()
    indegree[u] -= 1
    toposortlist.append(u)
    for v in AList[u]:
      indegree[v]-=1
      longestpathto[v] = max(longestpathto[v],longestpathto[u]+1)
      if(indegree[v]==0):
        longestpathq.addq(v)
  
  return(toposortlist, longestpathto)

In [ ]:
dagedges = [(0,2),(0,3),(0,4),(1,2),(1,7),(2,5),(3,5),(3,7),(4,7),(5,6),(6,7), (7,-1)]

In [ ]:
AList = AdjacencyList(dagedges)
AList

{0: [2, 3, 4], 1: [2, 7], 2: [5], 3: [5, 7], 4: [7], 5: [6], 6: [7], 7: []}

In [ ]:
longestpath(AList)

([0, 1, 3, 4, 2, 5, 6, 7], {0: 0, 1: 0, 2: 1, 3: 1, 4: 1, 5: 2, 6: 3, 7: 4})

#**WEEK-5**

###**Shortest path in weighted graphs**

- Single source shortest path
- All pairs shortest path

###**Single source shortest path**

In [ ]:
import numpy as np

In [ ]:
def WeightedMatrix(edges, size):
  Wmat = np.zeros(shape=(size, size, 2))
  for i, j, k in edges:
    (Wmat[i, j, 0], Wmat[i, j, 1]) = (1, k)
  return(Wmat)

In [ ]:
def dijkstra(Wmat, source):
  #(row, col, x) = Wmat.shape
  (row, col, x) = Wmat.shape
  (visited, distance) = ({}, {})

  infinity = np.max(Wmat)*row + 1   # max value

  for vertex in range(row):
    visited[vertex] = False
    distance[vertex] = infinity
  
  distance[source] = 0

  for u in range(row):
    nextd = min([distance[v] for v in range(row) 
                              if not visited[v]])
    nextvlist = [v for v in range(row) 
                    if not visited[v] and 
                        distance[v]==nextd]

    if(nextvlist == []):
      break
    nextv = min(nextvlist) 

    visited[nextv] = True 
    for v in range(col):
      if(Wmat[nextv, v, 0]==1 and (not visited[v])):
        distance[v] = min(distance[v], distance[nextv]+Wmat[nextv, v, 1])
  return(distance)

In [ ]:
edges = [(0, 1, 10), (0, 2, 80), (1, 0, 10), (1, 2, 6), (1, 4, 20), (2, 0, 80), (2, 1, 6), (2, 3, 70),
         (3, 2, 70), (4, 5, 50), (4, 1, 20), (4, 6, 5), (5, 4, 50), (5, 6, 35), (6, 4, 5), (6, 5, 10)]

In [ ]:
Wmat = WeightedMatrix(edges, 7)
Wmat

array([[[ 0.,  0.],
        [ 1., 10.],
        [ 1., 80.],
        [ 0.,  0.],
        [ 0.,  0.],
        [ 0.,  0.],
        [ 0.,  0.]],

       [[ 1., 10.],
        [ 0.,  0.],
        [ 1.,  6.],
        [ 0.,  0.],
        [ 1., 20.],
        [ 0.,  0.],
        [ 0.,  0.]],

       [[ 1., 80.],
        [ 1.,  6.],
        [ 0.,  0.],
        [ 1., 70.],
        [ 0.,  0.],
        [ 0.,  0.],
        [ 0.,  0.]],

       [[ 0.,  0.],
        [ 0.,  0.],
        [ 1., 70.],
        [ 0.,  0.],
        [ 0.,  0.],
        [ 0.,  0.],
        [ 0.,  0.]],

       [[ 0.,  0.],
        [ 1., 20.],
        [ 0.,  0.],
        [ 0.,  0.],
        [ 0.,  0.],
        [ 1., 50.],
        [ 1.,  5.]],

       [[ 0.,  0.],
        [ 0.,  0.],
        [ 0.,  0.],
        [ 0.,  0.],
        [ 1., 50.],
        [ 0.,  0.],
        [ 1., 35.]],

       [[ 0.,  0.],
        [ 0.,  0.],
        [ 0.,  0.],
        [ 0.,  0.],
        [ 1.,  5.],
        [ 1., 10.],
        [ 0.,  0.]]])

In [ ]:
Wmat.shape

(7, 7, 2)

In [ ]:
dijkstra(Wmat, 0)

{0: 0, 1: 10.0, 2: 16.0, 3: 86.0, 4: 30.0, 5: 45.0, 6: 35.0}

**Using adjacency list**

In [ ]:
def dijkstralist(WList, source):
  (visited, distance) = ({}, {})

  infinity = 1 + len(WList.keys())*(max([d for u in WList.keys() for (v, d) in WList[u]]))

  for i in WList.keys():
    (visited[i], distance[i]) = (False, infinity)

  distance[source] = 0
  for u in WList.keys():
    nextd = min([distance[v] for v in WList.keys() if not visited[v]])
    nextvlist = [v for v in WList.keys() if not visited[v] and (distance[v]==nextd)]

    if(nextvlist==[]):
      break

    nextv = min(nextvlist)
    visited[nextv] = True
    
    for (v,d) in WList[nextv]:
      if(not(visited[v])):
        distance[v] = min(distance[v], distance[nextv]+d)
  return(distance)

In [ ]:
def WeightedAdjacencyList(edges):
  WList = {}
  for i, j, k in edges:
    WList[i] = []
  for i, j, k in edges:
    WList[i] += [(j, k)]
  return(WList)

In [ ]:
edges = [(0, 1, 10), (0, 2, 80), (1, 0, 10), (1, 2, 6), (1, 4, 20), (2, 0, 80), (2, 1, 6), (2, 3, 70),
         (3, 2, 70), (4, 5, 50), (4, 1, 20), (4, 6, 5), (5, 4, 50), (5, 6, 35), (6, 4, 5), (6, 5, 10)]

In [ ]:
edges = [(1, 2, 3), (1, 4, 5), (2, 1, 2), (2, 4, 4), (3, 2, 1), (4, 3, 2)]

In [ ]:
WList = WeightedAdjacencyList(edges)
WList

{0: [(1, 10), (2, 80)],
 1: [(0, 10), (2, 6), (4, 20)],
 2: [(0, 80), (1, 6), (3, 70)],
 3: [(2, 70)],
 4: [(5, 50), (1, 20), (6, 5)],
 5: [(4, 50), (6, 35)],
 6: [(4, 5), (5, 10)]}

In [ ]:
dijkstralist(WList, 0)

{0: 0, 1: 10, 2: 16, 3: 86, 4: 30, 5: 45, 6: 35}

###**BELLMAN-FORD ALGORITHM**
- Single source shortest path
- Used in graph with negative edge weights

In [ ]:
def bellmanford(Wmat, s):
  (row, col, x) = Wmat.shape
  infinity = np.max(Wmat)*row+1 

  distance = {}
  for v in range(row):
    distance[v] = infinity

  distance[s] = 0
  for i in range(row):
    for u in range(row):
      for v in range(col):
        if Wmat[u, v, 0]==1:
          distance[v] = min(distance[v], Wmat[u, v, 1]+distance[u])
  return(distance)

In [ ]:
edges = [(0,1,10),(0,7,8),(1,5,2),(2,1,1),(2,3,1),(3,4,3),(4,5,-1),(5,2,-2),(6,1,-4),(6,5,-1),(7,6,1)]

In [ ]:
Wmat = WeightedMatrix(edges, 8)
Wmat

array([[[ 0.,  0.],
        [ 1., 10.],
        [ 0.,  0.],
        [ 0.,  0.],
        [ 0.,  0.],
        [ 0.,  0.],
        [ 0.,  0.],
        [ 1.,  8.]],

       [[ 0.,  0.],
        [ 0.,  0.],
        [ 0.,  0.],
        [ 0.,  0.],
        [ 0.,  0.],
        [ 1.,  2.],
        [ 0.,  0.],
        [ 0.,  0.]],

       [[ 0.,  0.],
        [ 1.,  1.],
        [ 0.,  0.],
        [ 1.,  1.],
        [ 0.,  0.],
        [ 0.,  0.],
        [ 0.,  0.],
        [ 0.,  0.]],

       [[ 0.,  0.],
        [ 0.,  0.],
        [ 0.,  0.],
        [ 0.,  0.],
        [ 1.,  3.],
        [ 0.,  0.],
        [ 0.,  0.],
        [ 0.,  0.]],

       [[ 0.,  0.],
        [ 0.,  0.],
        [ 0.,  0.],
        [ 0.,  0.],
        [ 0.,  0.],
        [ 1., -1.],
        [ 0.,  0.],
        [ 0.,  0.]],

       [[ 0.,  0.],
        [ 0.,  0.],
        [ 1., -2.],
        [ 0.,  0.],
        [ 0.,  0.],
        [ 0.,  0.],
        [ 0.,  0.],
        [ 0.,  0.]],

       [[ 0.,  0.],
        

In [ ]:
bellmanford(Wmat, 0)

{0: 0, 1: 5.0, 2: 5.0, 3: 6.0, 4: 9.0, 5: 7.0, 6: 9.0, 7: 8.0}

###BELLMAN-FORD

- Own approach

In [ ]:
def WeightedAdjacencyList(edges, size):
  WList = {}
  for i in range(size):
    WList[i] = []
  for (u, v, w) in edges:
    WList[u].append((v, w))
  return(WList)

In [ ]:
def bellmanfordown(WList, s):        # using adjacency list
  infinity = 1 + max([w for u in WList.keys()
                        for (v, w) in WList[u]])*len(WList.keys())
  distance = {}
  for u in WList.keys():
    distance[u] = infinity

  distance[s] = 0
  bellmanq = Queue()  # using a queue
  bellmanq.addq(s)

  while(not bellmanq.isEmpty()):
    u = bellmanq.delq()

    for (v, d) in WList[u]:
      if distance[v] > distance[u]+d:
        distance[v] = distance[u]+d  # whenever a vertex in updated it is added to the queue
        bellmanq.addq(v)
  return(distance)

In [ ]:
WList = WeightedAdjacencyList(edges, 8)
WList

{0: [(1, 10), (7, 8)],
 1: [(5, 2)],
 2: [(1, 1), (3, 1)],
 3: [(4, 3)],
 4: [(5, -1)],
 5: [(2, -2)],
 6: [(1, -4), (5, -1)],
 7: [(6, 1)]}

In [ ]:
bellmanfordown(WList, 0)

{0: 0, 1: 5, 2: 5, 3: 6, 4: 9, 5: 7, 6: 9, 7: 8}

##**ALL-PAIRS SHORTEST PATH**

In [ ]:
import numpy as np

In [ ]:
SP = np.zeros(shape=(3, 3, 4))
SP

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [ ]:
for i in range(3):
  for j in range(3):
    SP[i, j, 0] = 100
SP

array([[[100.,   0.,   0.,   0.],
        [100.,   0.,   0.,   0.],
        [100.,   0.,   0.,   0.]],

       [[100.,   0.,   0.,   0.],
        [100.,   0.,   0.,   0.],
        [100.,   0.,   0.,   0.]],

       [[100.,   0.,   0.,   0.],
        [100.,   0.,   0.,   0.],
        [100.,   0.,   0.,   0.]]])

#MINIMUM COST SPANNING TREE

- Prim's Algorithm
- Kruskal's Algorithm

###Prim's Algorithm
O(n^3)

In [ ]:
def primlist(WList):
  (tvertices, tedges, distance) = ({}, [], {})
  infinity = 1 + max([d for u in WList.keys()
                          for (v,d) in WList[u]])*len(WList.keys())
  for v in WList.keys():
    (distance[v], tvertices[v]) = (infinity, False)
  
  tvertices[0] = True
  for (v,d) in WList[0]:
    distance[v] = d 
  
  for i in WList.keys():
    (mindist, nextv) = (infinity, None)

    for u in WList.keys():
      for (v,d) in WList[u]:
        if tvertices[u] and (not tvertices[v]) and d < mindist:
          (mindist, nextv, nexte) = (d, v, (u,v))
    if nextv is None:
      break
    
    tedges.append(nexte)
    tvertices[nextv] = True
    for (v,d) in WList[nextv]:
      if not tvertices[v]:
        distance[v] = min(distance[v], d)  # update the distances of neigbours of most recently visited vertex
  return(tedges)

In [ ]:
def WeightedList(edges, size):
  WList = {}
  for i in range(size):
    WList[i] = []
  for (u,v,d) in edges:
    WList[u] += [(v,d)]
  return(WList)

In [ ]:
edges = [(0,1,10),(0,3,18),(1,0,10),(1,3,6),(1,2,20),(2,1,20),
          (2,4,8),(3,0,18),(3,1,6),(3,4,70),(4,3,70),(4,2,8)]

In [ ]:
WList = WeightedList(edges, 5)

In [ ]:
WList

{0: [(1, 10), (3, 18)],
 1: [(0, 10), (3, 6), (2, 20)],
 2: [(1, 20), (4, 8)],
 3: [(0, 18), (1, 6), (4, 70)],
 4: [(3, 70), (2, 8)]}

In [ ]:
primlist(WList)

[(0, 1), (1, 3), (1, 2), (2, 4)]

###**KRUSKAL'S ALGORITHM**

In [ ]:
def kruskal(WList):
  (edges, TE, component) = ([], [], {})

  for u in WList.keys():
    component[u] = u

  for u in WList.keys():
    for (v, d) in WList[u]:
      edges += [(d, u, v)]
  edges.sort()

  for (d, u, v) in edges:
    if component[u] != component[v]:
      TE.append((u,v))
      c = component[u]
      for w in WList.keys():
        if component[w]==c:
          component[w] = component[v] 
  return(TE)

In [ ]:
def WeightedList(edges, size):
  WList = {}
  for i in range(size):
    WList[i] = []
  for (u,v,d) in edges:
    WList[u] += [(v,d)]
  return(WList)

In [ ]:
edges = [(0,1,10),(0,3,18),(1,0,10),(1,3,6),(1,2,20),(2,1,20),
          (2,4,8),(3,0,18),(3,1,6),(3,4,70),(4,3,70),(4,2,8)]

In [ ]:
WList = WeightedList(edges, 5)

In [ ]:
kruskal(WList)

[(1, 3), (2, 4), (0, 1), (1, 2)]

#**WEEK-6**

###**UNION-FIND DATA STRUCTURE**

- Solving Kruskal's Algorithm using Union-Find Data Structure

In [ ]:
(Members, component, size) = ({}, {}, {})

In [ ]:
def find(v):
  return(component[v])

In [ ]:
def union(u, v):
  c_old = component[u]
  c_new = component[v]
  
  if(size[c_old] > size[c_new]):
    (c_old, c_new) = (c_new, c_old)
  
  for k in Members[c_old]:
    component[k] = c_new 
    Members[c_new] += [k]
    size[c_new] += 1

In [ ]:
def MakeUnionFind(WList):
  for u in WList.keys():
    Members[u] = [u]
    size[u] = 1

In [ ]:
def kruskal(WList):
  (edges, TE) = ([], [])
  for u in WList.keys():
    component[u] = u
  
  for u in WList.keys():
    for v,d in WList[u]:
      edges += [(d,u,v)]
  edges.sort()
  MakeUnionFind(WList)

  for (d, u, v) in edges:
    if find(u) != find(v):
      TE.append((u,v))
      union(u, v)
  return(TE)

In [ ]:
def WeightedList(edges, size):
  WList = {}
  for i in range(size):
    WList[i] = []
  for (u,v,d) in edges:
    WList[u] += [(v,d)]
  return(WList)

In [ ]:
edges = [(0,1,10),(0,3,18),(1,0,10),(1,3,6),(1,2,20),(2,1,20),
          (2,4,8),(3,0,18),(3,1,6),(3,4,70),(4,3,70),(4,2,8)]

In [ ]:
WList = WeightedList(edges, 5)

In [ ]:
kruskal(WList)

[(1, 3), (2, 4), (0, 1), (1, 2)]